version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: testHM   # 루트 비밀번호 지정
      MYSQL_DATABASE: HM        # 생성할 기본 DB 이름
      MYSQL_USER: HM                    # 새로 생성할 사용자
      MYSQL_PASSWORD: testHM       # 새로 생성할 사용자의 비밀번호
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: