spring:
  application:
    name: streamTest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/HM?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: HM
    password: testHM
    hikari:
      maximum-pool-size: 10
  sql:
    init:
      mode: never  # We're using our custom DatabaseInitializer instead

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
  packages-to-scan: hm.streamtest.controller

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: hm.streamtest.dto
